name: RPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Get release
       # id: get_release
       # uses: bruceadams/get-release@v1.2.2
       # env:
       #   GITHUB_TOKEN: ${{ github.token }}

      - name: Generating RPM Package    
        run: |
          sudo apt-get install rpm libcurl4-openssl-dev g++
          
          mkdir -p ./package/rpmbuild/SOURCES
          mkdir -p ./package/rpmbuild/SPECS
          
          printf '
          Name:           tess
          Version:        1.4
          Release:        0
          Summary:        Tess is an terminal emulator

          License:        GPL
          Source0:        tess.tar.gz

          %%description
          To add desc here !

          %%global debug_package %%{nil}

          %%prep
          %%setup -q

          %%build

          %%install
          rm -rf $RPM_BUILD_ROOT
          mkdir -p "$RPM_BUILD_ROOT/opt/tess"
          mkdir -p "$RPM_BUILD_ROOT/usr/bin"
          mkdir -p "$RPM_BUILD_ROOT/opt/tess-cli"
          mkdir -p "$RPM_BUILD_ROOT/usr/share/applications"

          cp tess.desktop "$RPM_BUILD_ROOT/usr/share/applications/"
          cp Tess.png "$RPM_BUILD_ROOT/usr/bin/Tess.png"

          cp -r app/* "$RPM_BUILD_ROOT/opt/tess/"
          ln -s "/opt/tess/tess" "$RPM_BUILD_ROOT/usr/bin/tess"

          cp -r cli/tess-cli "$RPM_BUILD_ROOT/opt/tess-cli/"
          ln -s "/opt/tess-cli/tess-cli" "$RPM_BUILD_ROOT/usr/bin/tess-cli"

          %%files
          /usr/bin/*
          /opt/*
          /usr/share/applications/*

          %%changelog
          * Sat Jul 03 2021 clement foure
          - first try
              
          ' > ./package/rpmbuild/SPECS/tess.spec
          
          mkdir -p ./package/rpmbuild/SOURCES/tess-${VERSION}/app
          mkdir -p ./package/rpmbuild/SOURCES/tess-${VERSION}/cli
          
          cp ./Tess.desktop ./package/rpmbuild/SOURCES/tess-${VERSION}/
          cp ./src/img/Tess.png ./package/rpmbuild/SOURCES/tess-${VERSION}/
          
          npm install
          npm run build
          cp -r ./dist/linux-unpacked/* ./package/rpmbuild/SOURCES/tess-${VERSION}/app/
          
          cd cli
          g++ main.cpp Class/*.cpp Utils/*.cpp Lib/*.cpp Lib/external/cpr/cpr/*.cpp -lpthread -lcurl -std=c++17 -o tess-cli
          cd ../
          cp ./cli/tess-cli ./package/rpmbuild/SOURCES/tess-${VERSION}/cli/
          
          tar zcvf ./package/rpmbuild/SOURCES/tess.tar.gz ./package/rpmbuild/SOURCES/*
          
          echo "loisting here"
          ls /home/runner/work/Tess/Tess/package/rpmbuild
          
          cd ./package
          echo "ls heeeererre"
          ls
          
          rpmbuild rpmbuild --define "_topdir `pwd`" /home/ -bb rpmbuild/SPECS/tess.spec
          ls ./package/rpmbuild/RPMS/x86_64/
          
        env:
          #VERSION: ${{ steps.get_release.outputs.tag_name }}
          VERSION: 0.4
        
      #- name: Upload release binary
       # uses: actions/upload-release-asset@v1.0.2
       # env:
       #   GITHUB_TOKEN: ${{ github.token }}
       # with:
       #   upload_url: ${{ steps.get_release.outputs.upload_url }}
        #  asset_path: ./package/debian/tess.deb
         # asset_name: Tess.deb
          #asset_content_type: application/octet-stream
