name: DEBIAN

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Get release
      #  id: get_release
      #  uses: bruceadams/get-release@v1.2.2
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}

      
      - name: Generating DEBIAN Package    
        run: |
          mkdir -p ./package/debian/tess/opt/tess/
          mkdir -p ./package/debian/tess/opt/tess-cli/
          npm install
          npm run build
          cp -r ./dist/linux-unpacked/* ./package/debian/tess/opt/tess/
          cd tess-cli
          g++ main.cpp Class/*.cpp Utils/*.cpp Lib/*.cpp Lib/external/cpr/cpr/*.cpp -lpthread -lcurl -std=c++17 -o tess-cli
          cp tess-cli ./package/debian/tess/opt/tess-cli/tess-cli
          cd ../
          
        #env:
        #  TEST: ${{ steps.get_release.outputs.tag_name }}
        
      #- name: Upload release binary
      #  uses: actions/upload-release-asset@v1.0.2
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
      #  with:
      #    upload_url: ${{ steps.get_release.outputs.upload_url }}
      #    asset_path: ./test.txt
      #    asset_name: test.txt
      #    asset_content_type: application/octet-stream
