name: TEST

on:
  push:

  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: echo "aaa"
        - run: mkdir -r .test/aa
        - run: echo "ert" > ./test/aa/bb.txt
