name: Updating AUR...

on:
  push:

  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Files
        uses: actions/checkout@v2
      
      - name: Update PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'tess-git'
          
<<<<<<< HEAD:.github/workflows/UpdateAUR.yml
      - name: Update AUR Package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
=======
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
>>>>>>> 6a1400692ed4f2fc6154db2d4c9f835c6299848a:.github/workflows/main.yml
        with:
          pkgname: tess-git
          pkgbuild: tess-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
