name: Updating Packages


  workflow_dispatch:

jobs:
  Updating_PKGBUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Files
        uses: actions/checkout@v2
      
      - name: Update PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'tess-nightly-git'
          
      - name: Update AUR Package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
        with:
          pkgname: tess-nightly-git
          pkgbuild: tess-nightly-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
